# Data Preprocessing | IBM SkillsBuild Internship

## Import the required libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Import the dataset

In [3]:
df = pd.read_csv('Data.csv')

In [4]:
df

Country   Age   Salary Purchased
0       India  44.0  72000.0        No
1   Thailand   27.0  48000.0       Yes
2   Indonesia  30.0  54000.0        No
3       China  38.0  61000.0        No
4       India  40.0      NaN       Yes
5       China  35.0  58000.0       Yes
6   Thailand    NaN  52000.0        No
7       India  48.0  79000.0       Yes
8   Indonesia  50.0  83000.0        No
9   Thailand   37.0  67000.0       Yes
10      India  25.0      NaN        No
11  Thailand   36.0  60000.0        No
12  Indonesia  42.0  64000.0       Yes
13      India   NaN  40000.0       Yes
14  Thailand   52.0  90000.0       Yes
15  Indonesia   NaN  55000.0        No
16      China  41.0      NaN       Yes
17      India  29.0  48000.0        No
18      China  43.0  70000.0       Yes

In [7]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [8]:
x

array([['India', 44.0, 72000.0],
       ['Thailand ', 27.0, 48000.0],
       ['Indonesia', 30.0, 54000.0],
       ['China', 38.0, 61000.0],
       ['India', 40.0, nan],
       ['China', 35.0, 58000.0],
       ['Thailand ', nan, 52000.0],
       ['India', 48.0, 79000.0],
       ['Indonesia', 50.0, 83000.0],
       ['Thailand ', 37.0, 67000.0],
       ['India', 25.0, nan],
       ['Thailand ', 36.0, 60000.0],
       ['Indonesia', 42.0, 64000.0],
       ['India', nan, 40000.0],
       ['Thailand ', 52.0, 90000.0],
       ['Indonesia', nan, 55000.0],
       ['China', 41.0, nan],
       ['India', 29.0, 48000.0],
       ['China', 43.0, 70000.0]], dtype=object)

In [9]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes',
       'No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    19 non-null     object 
 1   Age        16 non-null     float64
 2   Salary     16 non-null     float64
 3   Purchased  19 non-null     object 
dtypes: float64(2), object(2)
memory usage: 736.0+ bytes


## Solving for missing data

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])


In [12]:
print(x)

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 62562.5]
 ['China' 35.0 58000.0]
 ['Thailand ' 38.5625 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 62562.5]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' 38.5625 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' 38.5625 55000.0]
 ['China' 41.0 62562.5]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


## Encoding categorical data

In [15]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 0.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 40.0, 62562.5],
       [1.0, 0.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 0.0, 1.0, 38.5625, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 0.0, 1.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 0.0, 25.0, 62562.5],
       [0.0, 0.0, 0.0, 1.0, 36.0, 60000.0],
       [0.0, 0.0, 1.0, 0.0, 42.0, 64000.0],
       [0.0, 1.0, 0.0, 0.0, 38.5625, 40000.0],
       [0.0, 0.0, 0.0, 1.0, 52.0, 90000.0],
       [0.0, 0.0, 1.0, 0.0, 38.5625, 55000.0],
       [1.0, 0.0, 0.0, 0.0, 41.0, 62562.5],
       [0.0, 1.0, 0.0, 0.0, 29.0, 48000.0],
       [1.0, 0.0, 0.0, 0.0, 43.0, 70000.0]], dtype=object)

### Encoding the Independent Variable

In [21]:
x

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 0.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 40.0, 62562.5],
       [1.0, 0.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 0.0, 1.0, 38.5625, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 0.0, 1.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 0.0, 25.0, 62562.5],
       [0.0, 0.0, 0.0, 1.0, 36.0, 60000.0],
       [0.0, 0.0, 1.0, 0.0, 42.0, 64000.0],
       [0.0, 1.0, 0.0, 0.0, 38.5625, 40000.0],
       [0.0, 0.0, 0.0, 1.0, 52.0, 90000.0],
       [0.0, 0.0, 1.0, 0.0, 38.5625, 55000.0],
       [1.0, 0.0, 0.0, 0.0, 41.0, 62562.5],
       [0.0, 1.0, 0.0, 0.0, 29.0, 48000.0],
       [1.0, 0.0, 0.0, 0.0, 43.0, 70000.0]], dtype=object)

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)


In [19]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1])

### Encoding the Dependent Variable

## Splitting the dataset into the Training set and Test set

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)


## Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test= sc.transform(x_test)

In [25]:
print(x_train)


[[-0.5        -0.70710678 -0.5         1.6583124   2.22042763  2.385368  ]
 [ 2.         -0.70710678 -0.5        -0.60302269  0.31534835  0.07474013]
 [-0.5        -0.70710678 -0.5         1.6583124  -0.1067999  -0.81477265]
 [-0.5         1.41421356 -0.5        -0.60302269  0.14215933  0.07474013]
 [-0.5        -0.70710678  2.         -0.60302269 -1.58973093 -0.6463442 ]
 [ 2.         -0.70710678 -0.5        -0.60302269 -0.7237858  -0.30948729]
 [-0.5         1.41421356 -0.5        -0.60302269 -0.1067999  -1.82534339]
 [-0.5        -0.70710678 -0.5         1.6583124  -0.37740775  0.44844076]
 [-0.5         1.41421356 -0.5        -0.60302269  1.52767153  1.4590115 ]
 [-0.5         1.41421356 -0.5        -0.60302269 -1.76291995 -1.15162956]
 [-0.5        -0.70710678 -0.5         1.6583124  -0.55059678 -0.14105883]
 [ 2.         -0.70710678 -0.5        -0.60302269 -0.20421873 -0.0568446 ]
 [-0.5         1.41421356 -0.5        -0.60302269  0.83491543  0.8695119 ]
 [-0.5        -0.70710678

In [26]:
print(x_test)

[[-0.5         1.41421356 -0.5        -0.60302269 -2.45567606  0.07474013]
 [-0.5        -0.70710678 -0.5         1.6583124  -2.10929801 -1.15162956]
 [-0.5        -0.70710678  2.         -0.60302269  1.87404958  1.79586841]
 [ 2.         -0.70710678 -0.5        -0.60302269  0.6617264   0.70108345]]
